import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="flex flex-col min-h-screen">
          {/* Topbar */}
          <header className="w-full fixed top-0 left-0 z-50 px-8 py-4">
            <Topbar />
          </header>
          {/* Layout below Topbar */}
          <div className="flex flex-1 pt-[74px]  mx-4 "> {/* Adjust top padding based on Topbar height */}
            {/* Sidebar */}
            
              <Sidebar />
            
            {/* Main content */}
            <main className="flex-1 p-0  overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
